### ISSUE TITLE
No data to display

### ISSUE THREAD

**Issue by johnnieWa1ker** [artemnovichkov/xcode-timing#1]
After doing the installation and running my project a few times, I don't see any statistics data.
I can't find the `Documents/xcode-times.json` repository, this seems to be the problem.

Please let me know how I can help you better diagnose the problem.

Console output:

```
❯ xcode-timing show
No build data
+------+--------------+------------------+--------------------+
| Date | Project Name | Total Build Time | Average Build Time |
+------+--------------+------------------+--------------------+

+------+--------------+------------------+--------------------+
```

**Comment by artemnovichkov** [comment]
Hi! Thank you for the feedback! Could you please share your `xcode-times.json`?

**Comment by johnnieWa1ker** [comment]
I don't find such a file. Where should it be generated by default?

**Comment by artemnovichkov** [comment]
I've fixed the issue with the empty state.
https://github.com/artemnovichkov/xcode-timing/blob/41286ac88bd5259c2a445c6ae5b5c2f3176b632b/Sources/xcode-timing/Commands/Show.swift#L18-L21

But I'm not sure about the scripts. I guess they don't have required permissions. Could you please run `./start.sh` manually from Terminal and send me an output?

**Comment by johnnieWa1ker** [comment]
I think I figured out what the problem was - I thought that the executable files would be copied to `~/Library` after doing `make install`
Therefore, after setting up executable scripts in Xcode, I deleted the downloaded `xcode-timing` repository, which I should not have done.

After returning all the files to their places, I began to receive information about the assemblies 😎

**Comment by artemnovichkov** [comment]
Yes, it might be not so obvious. I'm going to improve installation and add Homebrew support in the future.
Anyway, thank you for using the tool! I hope it will help you in developer routine 🙂
